#! /bin/zsh

output * bg $wallpaper fill

# based on Base16 Seti UI
# Author: Appelgriebsch


# some global theme specific variables

set $cl_high #b4befe
set $cl_indi #9399b2
set $cl_back #1e1e2e
set $cl_fore #cdd6f4
set $cl_urge #f38ba8

# Colors                border   bg       text     indi     childborder
client.focused          $cl_high $cl_high $cl_fore $cl_indi $cl_high
client.focused_inactive $cl_back $cl_back $cl_fore $cl_back $cl_back
client.unfocused        $cl_back $cl_back $cl_fore $cl_back $cl_back
client.urgent           $cl_urge $cl_urge $cl_fore $cl_urge $cl_urge

for_window [class="^.*"] border pixel 1

gaps outer 5
gaps inner 5

bar {
  position top
  strip_workspace_name yes
  font Mononoki Nerd Font
  status_command i3status-rs ~/.config/i3status-rs/config.toml
  # tray_output none

  colors {
    background $cl_back
    focused_workspace $cl_back $cl_high $cl_back
    active_workspace $cl_back $cl_high $cl_back
    inactive_workspace $cl_back $cl_back $cl_fore
    urgent_workspace $cl_urge $cl_urge $cl_back
  }
}
