icons_format = "{icon}"

[theme]
theme = "ctp-mocha"

[theme.overrides]
idle_bg = "#b4befe"
idle_fg = "#1e1e2e"

[icons]
icons = "material-nf"

[icons.overrides]
bat = ["|E|", "|_|", "|=|", "|F|"]
bat_charging = "|^| "

[[block]]
block = "cpu"

[block.theme_overrides]
idle_bg = "#ba151d3"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon root: $available.eng(w:2) "

[block.theme_overrides]
idle_bg = "#F07178"

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[block.theme_overrides]
idle_bg = "#fb9f7f"

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[block.theme_overrides]
idle_bg = "#ffd47e"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "